spring.datasource:
  url: jdbc:h2:./camunda;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password: sa
spring.h2.console.enabled: true
camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
    lastName: Demo
  filter:
    create: All Tasks
  job-execution:
    wait-time-in-millis: 1000
    max-wait: 2000
  generic-properties:
    properties:
      deserializationTypeValidationEnabled: false
      #deserializationAllowedClasses: org.camunda.bpm.example.release_presentation.Harmless
server.port: 8080
